create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 16),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

alter table public.scores enable row level security;

drop policy if exists "Anyone can read top scores" on public.scores;
create policy "Anyone can read top scores"
  on public.scores
  for select
  using (true);

drop policy if exists "Anyone can submit scores" on public.scores;
create policy "Anyone can submit scores"
  on public.scores
  for insert
  with check (true);

create index if not exists scores_score_desc_idx
  on public.scores (score desc, created_at asc);
