create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  nickname text not null check (char_length(nickname) between 1 and 16),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.scores
  add column if not exists updated_at timestamptz not null default now();

alter table public.scores enable row level security;

create unique index if not exists scores_nickname_key
  on public.scores (nickname);

drop policy if exists "Anyone can read top scores" on public.scores;
create policy "Anyone can read top scores"
  on public.scores
  for select
  using (true);

drop policy if exists "Anyone can submit scores" on public.scores;
create policy "Anyone can submit scores"
  on public.scores
  for insert
  with check (true);

drop function if exists public.submit_score(text, integer);
create function public.submit_score(player_nickname text, player_score integer)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.scores (nickname, score)
  values (
    trim(regexp_replace(left(player_nickname, 16), '\s+', ' ', 'g')),
    greatest(player_score, 0)
  )
  on conflict (nickname)
  do update set
    score = greatest(public.scores.score, excluded.score),
    updated_at = now();
$$;

grant execute on function public.submit_score(text, integer) to anon;
grant execute on function public.submit_score(text, integer) to authenticated;

create index if not exists scores_score_desc_idx
  on public.scores (score desc, updated_at asc);
